-- --------------------------------------------------------------------
-- MySQL Audit Trigger
-- Copyright (c) 2014 Du T. Dang. MIT License
-- https://github.com/hotmit/mysql-sp-audit
-- --------------------------------------------------------------------
DROP PROCEDURE IF EXISTS `sp_generate_remove_audit`;

CREATE PROCEDURE `sp_generate_remove_audit` (IN audit_schema_name VARCHAR(255), IN audit_table_name VARCHAR(255), OUT script LONGTEXT)
main_block: BEGIN

    SET script := CONCAT(
        '-- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n',
        '-- --------------------------------------------------------------------\n',
        '-- Audit Removal Script For `',audit_schema_name, '`.`', audit_table_name, '` \n',
        '-- Date Generated: ', NOW(), '\n',
        '-- Generated By: ', CURRENT_USER(), '\n',
        '-- BEGIN\n',
        '-- --------------------------------------------------------------------\n\n',
        'DROP TRIGGER IF EXISTS `', audit_schema_name, '`.`', audit_table_name, '_AINS`;\n',
        'DROP TRIGGER IF EXISTS `', audit_schema_name, '`.`', audit_table_name, '_AUPD`;\n',
        'DROP TRIGGER IF EXISTS `', audit_schema_name, '`.`', audit_table_name, '_ADEL`;\n',

        '\n\n',
        '-- --------------------------------------------------------------------\n',
        '-- END\n',
        '-- Audit Removal Script For `',audit_schema_name, '`.`', audit_table_name, '`\n',
        '-- --------------------------------------------------------------------\n\n'
    );

END;